# serial_bridge.param.yaml

serial_bridge:
  ros__parameters:

    # Odometry frame id
    odometry_frame_id      : "odom"
    odometry_child_frame_id: "base_footprint"

    # Serial port settings
    port_path: "/dev/ttyUSB0"
    baud_rate: 115200

    # ERP42 parameters
    max_speed_mps      :  7.00 # m/s
    max_steering_deg   : 25.00 # deg
    steering_offset_deg:  0.00 # deg